<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<div class="footer">
        <div class="footer-inner">
            <!-- #section:basics/footer -->
            <div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">优蛋科技</span>
							版权所有 Copyright &copy; 2016-2017
						</span>

                &nbsp; &nbsp;
                <!--
						<span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>
						</span>
				-->
            </div>

            <!-- /section:basics/footer -->
        </div>
    </div>